
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/userspring
        username: postgres
        password: 12345

spring:
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: update
                